### ISSUE TITLE
Variable parsing breaks when value contains '='

### ISSUE THREAD

**Issue by Chris-Greaves** [Chris-Greaves/pencil#1]
When setting a variable containing a `=` in the value, it isn't parsed correctly and therefore brakes configs.

Example below:
```yaml
  pencil:
    image: ghcr.io/chris-greaves/pencil:v0.0.1
    environment:
      - AZURE_STORAGE_ACCOUNT="devstoreaccount1" # Default Azurite storage account
      - AZURE_STORAGE_KEY="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==" # Default azurite storage key
    command:
      - "/mnt/configs/"
    volumes:
      - ./tempo/tempo.yml:/mnt/configs/tempo.yml
      - ./loki/loki.yml:/mnt/configs/loki.yml
```
